
spring:
  profiles:
#    active: @profileActive@
    include: @profileActive@
#    active: webapi_dev,service_dev,ability_dev,mqredis_dev,dao_dev
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  http:
    multipart:
      enabled: false
      max-file-size: 10MB
      max-request-size: 20MB
    encoding:
      enabled: true
      force: true
      charset: UTF-8
