
logging:
  config: classpath:log4j2-redis_dev.yml

spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: root
    timeout: 3000
    pool:
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
